### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#10]
I understood from my latest discussion with Michael that users should login first before seeing the bets.

I don't mind seeing the bests first before needing to login, I just want to make sure we're on the same page.

Can you delete my useraccount again (hans@geonova.no) so I can test the sign-up process?

**Comment by mladjan** [comment]
We managed it that users can see bets before login. They need login before comment or betting.
Your account will be deleted in next couple of minutes.

**Comment by diplomod** [comment]
OK
