### ISSUE TITLE
Change wording in final submit button

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#11]
We use "Place your bet" on several steps. Therefore, I would like to use "Submit" instead of "Place your bet" on the green button on the bottom of the selection page. Users will then more easily understand that this was the final step.
![image9](https://cloud.githubusercontent.com/assets/7487883/5165578/a8aed2cc-73e6-11e4-8c76-d4202776b9e0.png)

**Comment by mladjan** [comment]
Done

**Comment by diplomod** [comment]
OK
