### ISSUE TITLE
Admin Area/ Editing

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#12]
Is there a way how I can edit texts?
Where do the new WellBets come from? How does that process look like?
(is it automatically filled in to the App when I add a new one in Wordpress or do I need to do some extra editing?)

Also, where can I edit the banner in the app?

**Comment by mladjan** [comment]
Hi,

all wellbets are pulled directly from your wordpress database. Right now we have test development server which isn't connected to your live database.

**Comment by diplomod** [comment]
Excellent - as soon as it's working we can connect it to the test environment on http://dokuhl.de/geonova/well-bet-page/the-ivory-prospect/ and I can add more wellbets there. or is it already connected to that system?

**Comment by mladjan** [comment]
No, everything is on our dev server. Will be migrated when we finish all bug fixes.
