### ISSUE TITLE
Sign-up process: Terms & Conditions

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#13]
Are the Terms & Conditions sourced from geonova.no (http://www.geonova.no/about/terms-conditions/) or "hard coded"?
![image12](https://cloud.githubusercontent.com/assets/7487883/5200716/092795f2-7569-11e4-8b28-9b2e47156dde.png)

**Comment by mladjan** [comment]
It's hardcoded. The reason is because we needed to rewrite this HTML to support mobile devices. It has additional CSS for better display on iPhone.

**Comment by diplomod** [comment]
OK, fine. How do I update the text in the future? DO I need to go through you guys?

**Comment by mladjan** [comment]
These two screens can be put on our webserver, and updated instantly, but we need to edit them becuse in some cases we have these "custom" local URLs.

**Comment by diplomod** [comment]
OK
