### ISSUE TITLE
Sign-up process: Text in "About me" field does not disappear when entered

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#14]
In the other fields of registration, the text that is in the field disappears when I click in it.
Only in "About me", it remains and becomes part of my entered text:

![image11](https://cloud.githubusercontent.com/assets/7487883/5200732/3ef3c71e-7569-11e4-91a0-29010cc8b7c0.png)

**Comment by mladjan** [comment]
It worked for me. Can you check your spam folder?

**Comment by diplomod** [comment]
Nope. I tried to reinstall the app in order to be able to regisiter again, but currently I can not retry:
![image13](https://cloud.githubusercontent.com/assets/7487883/5200816/4001e6a8-756a-11e4-99cd-554d073079e0.png)

I suggest you check this data base issue before I continue testing as it makes it pretty impossible at the moment.

**Comment by mladjan** [comment]
Sorry for that. we are working right now on the server, and this is why you see these issues. Let you know when you can test it again.

**Comment by mladjan** [comment]
I just realised that I commented on wrong issue. Sorry for that. I fixed the issue with About Me placeholder and it will be available in next build.

**Comment by diplomod** [comment]
Now it dissapears, but behaves differently than the other fields:
When I leave the field again, it remains empty. While in other fields, the infotext re-appears if I have not entered anything. All fields must behave exactly the same (it's not about that tiny detail, but about how clean is the code)

![2014-11-27 19 45 03](https://cloud.githubusercontent.com/assets/7487883/5221022/6a83ac98-7670-11e4-8357-136d73b198ba.png)

**Comment by mladjan** [comment]
This is different because about me is UITextView control, and other fields are UITextFields. Difference is that TextView takes more then one line of text, and has different behaviour. I will try to make ti working like other fields.

**Comment by diplomod** [comment]
All right - I don't get the difference; however, the user does not differentiate either I assume, so it would be good if the fields just behave identical.
