### ISSUE TITLE
Sign-up process: Sign-up does not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#15]
I don't receive a registration email.
Is it active already?

**Comment by mladjan** [comment]
Please, check it again in next build.

**Comment by diplomod** [comment]
No email, no SPAM.

**Comment by mladjan** [comment]
Hi.
Are you sure that you entered email in the right format without any typos?
I just made account and got email: http://cl.ly/image/340l2W0y201N
We are using "buddypress" functions for registration. What email you are using to register, so we can test with this example?

**Comment by diplomod** [comment]
I cannot be sure; I will test again. But before that: Is it the latest build in crashlytics app now (v1.0 3)?

**Comment by mladjan** [comment]
No, new build will be sent today (1.0 build 4)
