### ISSUE TITLE
Sign-up process: "Forgot Password?" link does not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#16]
When I click on it, nothing happens:

![image10](https://cloud.githubusercontent.com/assets/7487883/5200747/774f6e74-7569-11e4-9f31-b8f80e410b99.png)

**Comment by mladjan** [comment]
I realised that we don't have design for this. I suggest this to be the screen with email field and one confirm button. Is this ok for you?

**Comment by diplomod** [comment]
please check here: http://www.geonova.no/
it must fit together

**Comment by diplomod** [comment]
Now I get to a blank page with no possibility to go back. So I had to delete and re-install:

![2014-11-27 19 41 44](https://cloud.githubusercontent.com/assets/7487883/5220984/9749a814-766f-11e4-85bb-b9b52a4a09ea.png)

**Comment by mladjan** [comment]
Fixed in next build

**Comment by diplomod** [comment]
Well; I just installed v1.0(3) and its the same...
