### ISSUE TITLE
Sign-up Process: I can enter with any password I like

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#17]
Is it still in "dummy" mode and not connected to the database?

**Comment by mladjan** [comment]
We had a problem with database on our test server. Please, test it again.

**Comment by diplomod** [comment]
I just typed in just whatever, not even an email address, no @ sign or . - I can perfectly log in.
So the login does not work at all.

**Comment by mladjan** [comment]
Bug fixed on server, sorry for inconvenience.
