### ISSUE TITLE
"See Details" button in closed and open WellBets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#18]
In order to differentiate more closed from open bets:

Closed bets should always have "See Results" button instead of "See Details" (after a bet is closed there will be always a page with the analysis behind this button).

**Comment by mladjan** [comment]
When you say "See Details", you mean "More info"?
http://cl.ly/image/0q2l023h151X

**Comment by diplomod** [comment]
Actually no. "See Results" should be shown in this screen, but instead of the dark grey "See Details" button:
![02_02_geonova_wellbet_list_my](https://cloud.githubusercontent.com/assets/7487883/5251387/4105f934-7995-11e4-8d5b-7af1a1b00661.png)

See also #4 : I suggested to take out the "Active" & "Completed" and differentiate only by the button. For bets in "My WellBets" that re still running, the button says "See Details" (light grey is fine). For bets in "My WellBets" that are closed, the button should say "See results" (dark grey is fine).

**Comment by mladjan** [comment]
Ok, got it :)

**Comment by mladjan** [comment]
I was not able to get results without some API modifications. Will consult API developer today.

**Comment by mladjan** [comment]
Ok, done this right now.
