### ISSUE TITLE
Sign-up Process: Infotexts in fields should disappear when activated

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#19]
I am used to from other apps that when you click in a field, the infotext that was in that field disappears.
Here it doesn't, only when I start typing. SHould be as in all other apps.
See also #14 
![2014-11-27 19 44 52](https://cloud.githubusercontent.com/assets/7487883/5221007/21946c34-7670-11e4-9a62-9421694e25c6.png)

**Comment by mladjan** [comment]
You are not right, this is native behaviour of UITextField with placeholder.
I can change it, but when someone is in focus of the field (tapped next on keyboard), it needs to see what to enter before start typing. Let me know the final decision.

**Comment by diplomod** [comment]
OK - I suggest you display the info content until the user starts typing. Please make sure it's behaving identical in all fields.

**Comment by mladjan** [comment]
Done, will be available in next build (4)
