### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#2]
Improve the readability by 
- bigger font
- darker font
  ![image](https://cloud.githubusercontent.com/assets/7487883/5165393/31528b44-73e4-11e4-90aa-5b583dc7c5fa.png)

**Comment by mladjan** [comment]
Ok, done. We are using right now 16px instead of 14px, and #5c5c5c for text.

**Comment by diplomod** [comment]
Do I need an update of the app? Still looks the same for me.

**Comment by diplomod** [comment]
It's still far too small and too light. I am not sure if it is any different in the new version. I can hardly read it.

![2014-11-27 19 39 42](https://cloud.githubusercontent.com/assets/7487883/5220961/32ce407a-766f-11e4-9a6e-ee8f27b53ac7.png)

**Comment by mladjan** [comment]
On this screenshot you can see difference in colour and font size. But I changed font right now from light to regular, and colour is darker. Test this in next build 4.
