### ISSUE TITLE
App slow

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#25]
The app is sometimes really slow and takes too much time when loading.

![2014-11-27 19 39 26](https://cloud.githubusercontent.com/assets/7487883/5221219/f069fc50-7674-11e4-9dba-83d9ca606048.png)

**Comment by mladjan** [comment]
This is because it's on our slow dev server, this will be much faster when we switch on production server.

**Comment by diplomod** [comment]
of course, good. Let's kep an eye on that though.
