### ISSUE TITLE
Results page optimization

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#26]
2 things:

1) The results are displayed too small - this should be bigger (at least on iPhone 4 it's hard to read)
. Eventually it helps when the background is white instead of grey.

2) the effect that the headlines stick and the content is kind of moving below the headlines is fancy, but in this place useless. Please take it out.

![2014-11-27 19 48 10](https://cloud.githubusercontent.com/assets/7487883/5221221/f9b3f0a4-7674-11e4-8407-49784852c7af.png)

**Comment by mladjan** [comment]
1) This can be done. Will be available in next build
2) This is native behaviour of UITableView and can't be turned off in new versions of iOS (there was some hack for iOS6). It's hard to make this screen generic without UITableView, and this is something we need to live with.

**Comment by mladjan** [comment]
@diplomod Can I get feedback about point 2?

**Comment by diplomod** [comment]
Well, if we can't change it then we need to live with it as you say. Could be worse :)
