### ISSUE TITLE
Login & Sign-up process: Keypad does not diappear

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#27]
At least on iPhone 4 I have real trouble signing in or up because the keypad covers the buttons.
Is this different on a bigger screen? Is there a solution for iPhone 4 as it is still used by many people.

![2014-11-27 19 45 03](https://cloud.githubusercontent.com/assets/7487883/5221241/9c5c5620-7675-11e4-832e-ee845e5b6c3e.png)

**Comment by mladjan** [comment]
There are two ways to close keyboard:
1. Tap on Done on keyboard (http://cl.ly/image/071W1G3k0d2Y)
2. Tap on white background

This is design patter used for iOS

**Comment by diplomod** [comment]
OK - I used to have an Android, there you have an extra button for taking away the keyboard. Anyway, fine, thanks for the hint.

**Comment by diplomod** [comment]
On iPhone 4 it still is quite inconvenient, but let's leave it.
