### ISSUE TITLE
Home: Green lines design element or function?

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#28]
Just a question: I thought the green lines on home indicate the loading process. Or are they ment only as design element?
(below "powed by..." and above "More information"-button
![2014-12-08 07 12 21](https://cloud.githubusercontent.com/assets/7487883/5335593/7472bac4-7ead-11e4-9ae9-05fdfcd21d56.png)

**Comment by mladjan** [comment]
They are design element, we don't need loading progress bars :)
