### ISSUE TITLE
Open vs. closed WellBets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#3]
The one WellBet that is in the list is enlisted in "Open WellBets", yet has the lable "closed"
![image 1](https://cloud.githubusercontent.com/assets/7487883/5165407/5312ba9c-73e4-11e4-8b8f-5e07c71436f9.png)

**Comment by mladjan** [comment]
I was looking in the wrong property. Fixed, will be available in build 3.
Btw, I will just comment them, when you confirm that bug is fixed, close this issue :)
