### ISSUE TITLE
Black screen after going back from "Closed Wellbets"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#30]
I went to "Closed WellBets" and then back and got a black screen. After that, I tried to go to "Open WellBets" and "My WellBets", and I could switch the menu items including the error message, but then app crashed:
![2014-12-08 07 14 40](https://cloud.githubusercontent.com/assets/7487883/5335624/440fc4a2-7eae-11e4-9f28-af02ffd8c6a9.png)
![2014-12-08 07 14 43](https://cloud.githubusercontent.com/assets/7487883/5335625/440feb12-7eae-11e4-9ef8-45fff2be44ab.png)
![2014-12-08 07 14 54](https://cloud.githubusercontent.com/assets/7487883/5335626/44123c50-7eae-11e4-88de-87cebc0997bd.png)

**Comment by mladjan** [comment]
@diplomod what happened before that? Like for #39 I can't reproduce this on my iPhone 6 with iOS8.
Edit: I reproduced it on iOS7, sorry. Will fix it.
