### ISSUE TITLE
"WellBet"/"WellBets" instead of "Wellbet"/"Wellbets" 

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#31]
WellBet schould always be written with a capital "B". I have overseen this in the design round, I hope you can change it easily.

**Comment by mladjan** [comment]
Changed this on home page. Let me know if I missed somewhere.

**Comment by diplomod** [comment]
In my latest V5 still "Wellbet" in the menu (Open Wellbets, My Welbets, Closed Wellbets)

**Comment by mladjan** [comment]
This will be visible in next build :) (build 6)

**Comment by diplomod** [comment]
Looks good.
