### ISSUE TITLE
Password recovery German

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#32]
The password recovery is in German. I just wonder if that is based on the settings in the test environment and will be in English on the live server?
![2014-12-08 07 19 53](https://cloud.githubusercontent.com/assets/7487883/5335646/b9cbddca-7eae-11e4-98e9-7113abf1f730.png)

**Comment by mladenbl** [comment]
It's using default wordpress language for that message(depends on which one you choose when you installed wordpress), but we can manually create English message if you want.

**Comment by diplomod** [comment]
Then it should be fine on the live environment, let's leave it and get back to this only if we have to.
