### ISSUE TITLE
Password Recovery only works on 2nd attempt

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#33]
In the first attempt, the password recovery tells me that the key has expired (Text to red line):
![2014-12-08 07 20 34](https://cloud.githubusercontent.com/assets/7487883/5335654/d8e6f06e-7eae-11e4-865c-390f67c69b69.png)
On the 2nd attempt it worked then. 
I don't know if this is determined by the test environment settings, but anyway it should work on the first attempt.

**Comment by mladjan** [comment]
Fixed, will be available in next build (6)

**Comment by diplomod** [comment]
Works perfectly now.
