### ISSUE TITLE
Password Recovery leads to website, not App

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#34]
The password recovery leads me after the completed process and login to the website - which is irritating for app users.
Can user be re-directed to the app if they have come from there?

Same goes for new registrations.

![2014-12-08 07 24 02](https://cloud.githubusercontent.com/assets/7487883/5335673/25e5d13c-7eaf-11e4-9288-d407119f4f0e.png)

**Comment by mladjan** [comment]
No, there is a problem that this part of the system is controlled by wordpress and wordpress plugin you used. We can just send him on web to finish, and return itself back to app.
