### ISSUE TITLE
Comments: Remove headline "New Comment"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#35]
The headline "New Comment" on the commenting screen is irritating as it is the same style as the buttons. But since there is "Comment" as another headline in the screen yet again and we have "Comment" as a command now, you can remove the headline "New Comment":

![2014-12-08 07 25 36](https://cloud.githubusercontent.com/assets/7487883/5335685/6cc47a04-7eaf-11e4-8e09-c400a1f8c4b2.png)

**Comment by mladjan** [comment]
fixed in build 6
