### ISSUE TITLE
Comments should be shown in "More information" screen

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#36]
The comments that have been submitted to a bet should be shown on the "More information" screen somehow, not only hidden behind the "Comment" button at the bottom.

![image 4](https://cloud.githubusercontent.com/assets/7487883/5335709/e7f155e4-7eaf-11e4-881c-af7957d8b2b2.png)

Maybe the "Comment" button can have a little coloured notification button on it (like the notifications on apps on my phone's home screen) with the number of comments - if there are any?
Kind of like this:
![screen shot 2014-12-08 at 07 58 23](https://cloud.githubusercontent.com/assets/7487883/5335716/0a3b2b02-7eb0-11e4-9f3b-05d507f8b564.png)

**Comment by mladjan** [comment]
First request can't be done because this is we are parsing html from wordpress to show in more info.
About red badges, they are reserved in iOS only for missed push notifications, and can't be used for anything except this.

**Comment by diplomod** [comment]
The red badges are just an example, any kind of hint is ok. I have talked to Michael about this, he said you guys would discuss this.

**Comment by diplomod** [comment]
Any ideas about how to make the comments visible?
What I mean is that users should see immidiately when they open a prospect details page whether there are any comments. E.g. it's great if we could have "Comments (0)" or "Comments (3)" in the button instead of only "Comment"

**Comment by mladjan** [comment]
Added number of comments in format "Coments (23)"

**Comment by diplomod** [comment]
that is really great and totally serves the purpose.
