### ISSUE TITLE
Submit does not work any more

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#37]
I can't submit any bets - the button freezes with white at the place of the font:
![2014-12-08 07 28 00](https://cloud.githubusercontent.com/assets/7487883/5335754/e0092446-7eb0-11e4-9126-fe1cc9b4c665.png)
![2014-12-08 07 28 40](https://cloud.githubusercontent.com/assets/7487883/5335755/e00a41e6-7eb0-11e4-8607-769c3b269367.png)

**Comment by mladjan** [comment]
Ah, forgot to connect new button. Sorry for this. Fixed, will be available in new version (build 6)

**Comment by diplomod** [comment]
not fixed yet, so not closed (/for the protocoll: Issues can only be closed when I have tested them and consider them closed. Otherwise we lose overview)

**Comment by mladjan** [comment]
The same, next build (6)

**Comment by diplomod** [comment]
Works now
