### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#39]
The app continuously crashed - see also #30  
E.g. I go in a closed bet, then I go back, I go to open bets, try to open one - and there I land on the home screen.

**Comment by mladjan** [comment]
@diplomod can you please try to reproduce this, I can't reproduce this crash, and I got crash report which is so generic and can't reproduce it on my phone :|

**Comment by diplomod** [comment]
Well, I am switching between Open WellBets, My Wellbets, Closed WellBets etc. and then it happens. Can't find a logic. let's see how it behaves in the live environment, Meanhwile open.

**Comment by mladjan** [comment]
Found it and fixed. Will be available in next build (6)

**Comment by diplomod** [comment]
Yes, seems to work fine now.
