### ISSUE TITLE
Star

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#4]
I don't get what the star is good for.
And it's not aligned with the lable "closed"

![image 2](https://cloud.githubusercontent.com/assets/7487883/5165413/6b8858fc-73e4-11e4-9fb4-33fc01f05df5.png)

**Comment by mladjan** [comment]
Ok, I think I fixed alignment (check again please), but not sure what do you think about star? This is the same star you approved in designs :)

**Comment by diplomod** [comment]
I have not approved it yet. I sent an email about this to Michael with questions yet he must have overseen it. I clarify.

**Comment by mladjan** [comment]
Ah, ok. Will check this with Michael and Igor (designer) before we make any changes to that screen.

**Comment by diplomod** [comment]
2 things:

1) The star can be used for one case only: A WellBet (either closed or open) that I as a user have not opened yet has a filled star. That will catch my attention. As soon as the user has opened the bet once, the star is blank (as it is now)

2) Take out "active" and "completed": They are the same as closed and open WellBets and therefore useless info
- When I am in the area "Open WellBets", all bets are open, so I don't need the info "active"
- When I am in the area "Closed WellBets", all bets are closed, so I don't need the info "completed"
- Only when I am in the area "My WellBets", a differentiation makes sense (a user can have placed bets on a WellBets that is still open for others or a WellBet that is now closed). But we don't do this differentiation with an additional lable; instead we change the green button:
  -- Closed WellBets in "My WellBets": Button says "See Results" (as all closed bets should have)
  -- Open WellBets in "My WellBets": Button says "See Details"

**Comment by diplomod** [comment]
The star works fine now and I think the user gets the function.Is it possible to align it more to the left, closer to the date? It looks a little lost now in the middle of the line ;)

**Comment by mladjan** [comment]
Any good? http://cl.ly/image/1s0N3P2k1o3R :)

**Comment by diplomod** [comment]
Thanks - I suggest 3-4 px down still and closer to the "4" of "2014"
