### ISSUE TITLE
Change Error message from "Problem... " to "Please ..."

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#42]
![2014-12-26 18 07 37](https://cloud.githubusercontent.com/assets/7487883/5558747/fcdbe0dc-8d32-11e4-8960-361a6e80c579.png)
Don't use "Problem".
If possible, please change to "Please login / You need to be logged in to access this page."

**Comment by mladjan** [comment]
fixed in build 11

**Comment by diplomod** [comment]
Can't reproduce now, but I am sure it's fine - thanks
