### ISSUE TITLE
Where does the text in T&C come from?

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#43]
If it's in the App, I need to change it eventually before golive

**Comment by mladjan** [comment]
Yes, it's in our app, and I got it from our designer Igor.

**Comment by mladjan** [comment]
Please @diplomod , send me updated text for this screen.

**Comment by diplomod** [comment]
Please use this text: 
http://www.geonova.no/about/terms-conditions/

**Comment by mladjan** [comment]
Updated in build 12.
