### ISSUE TITLE
Registration of a new user did not work

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#45]
May be a mail server problem. Any way, I could not register a news user.

**Comment by mladjan** [comment]
it works on the same way like web, because we are using wordpress for registration. This can be wordpress or email problem, we can't change here nothing to improve this.

**Comment by diplomod** [comment]
OK - I tried again, but no success. I guess it's on the test environment side then. I will test it when we switch to the live environment. There it must work.
