### ISSUE TITLE
Shortcode for quiz is displayed as text in “More Information"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#46]
Here we need to find a solution I understand the app gets the info from the quiz widget and integrates it in the seperate page behind "Place your bet" - which is fine. But the text displays still the shortcode in the intro nonetheless:

![2014-12-26 18 50 23](https://cloud.githubusercontent.com/assets/7487883/5558782/0c9e597c-8d34-11e4-8ff6-5634661475a9.png)

**Comment by mladjan** [comment]
Fixed in build 11

**Comment by diplomod** [comment]
correct, looks good, thanks
