### ISSUE TITLE
Comments are not synchronized

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#49]
Several comments in App, but non on the website ( e.g. http://dokuhl.de/geonova/well-bet-page/640512-1-lindarormen/)

**Comment by mladjan** [comment]
Fixed in build 11

**Comment by diplomod** [comment]
Yes - the comments are shown correctly it seems. But the profile pictures are not shown respectively strange icons. Can we show the correct profile pictures?

Strange icons:
![2014-12-29 19 56 43](https://cloud.githubusercontent.com/assets/7487883/5572674/f558a036-8fa1-11e4-8372-380f1bc05953.png)

The user "Hans Gmail" has a profile picture:
![bild](https://cloud.githubusercontent.com/assets/7487883/5572716/8255d1b6-8fa2-11e4-84de-3ef259ff66b5.jpeg)
![screen shot 2014-12-29 at 21 34 10](https://cloud.githubusercontent.com/assets/7487883/5572721/89c45774-8fa2-11e4-8767-363c8ce64af7.png)

**Comment by mladjan** [comment]
There was a problem with library I'm using for gravatar images. Wordpress in general is using gravatar service to get the avatar from email.
As you can see in build 12, for my account there is a avatar.
Hans Gmail doesn't have gravatar image, and you can check it here: https://en.gravatar.com/site/check/

**Comment by diplomod** [comment]
Thanks. I don't know how geonova.no is working in this regard.
@Immoz Can you let us know if a) geonova.no is using gravatar and b) if we therefore will see avatar pictures in the live version of the app or not? Thanks for your input.

**Comment by Immoz** [comment]
Geonova first checks if the user has uploaded an avatar on profile settings. If there was no image uploaded on geonova, it continues to check for gravatars by the given email. To fetch the uploaded images on geonova i use for example this php-code:
bp_core_fetch_avatar( array( ‘item_id’ => $userid) );

or without html (don't tried this code):
bp_core_fetch_avatar( array( ‘item_id’ => $userid, ‘html’ => false ) );
