### ISSUE TITLE
Pictures/Graphics enlarged

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#5]
When I click on a picture, it is opened in a seperat screen in original size. That's fine.
But I cannot go back to the WellBet. I need to get back to home.

![image 4](https://cloud.githubusercontent.com/assets/7487883/5165429/9b20e020-73e4-11e4-8e8c-db7820dc37de.png)

**Comment by mladjan** [comment]
Because this is generic screen (we are loading generic HTML from wordpress here), it's risky to open all urls inside the app. So, the cleaner solution is to open all URLs in Safari. Please check how it works in next build and let me know if this is fine for you.

**Comment by diplomod** [comment]
URLs in Safari is ok, but graphics must be loaded in the app in a higher resolution than displayed in the app. So there is no need to open pics in Safari. 
Plus pictures are no URLs.

We should avoid leaving the app as much as possible. Whenever Safari opens, I need to go back to home and open the app again.

**Comment by mladjan** [comment]
Ok, all images right now are opening in app (like in tweetbot app, with some fancy physics, zoom option,...). I hope you will like it :)
