### ISSUE TITLE
Empty form for placing a bet

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#51]
In one bet a had an empty from - worked on the Web, shortcode should be correct
![2014-12-26 18 53 02](https://cloud.githubusercontent.com/assets/7487883/5558793/e40181aa-8d34-11e4-8aac-47fefa2a2f0b.png)

**Comment by mladjan** [comment]
This is the problem with test WellBet on the server.

**Comment by mladenbl** [comment]
Can you please send us admin login details for website?

**Comment by diplomod** [comment]
I made your user with mladjan@blgrd.co an admin on dohul.de/geonova

**Comment by mladenbl** [comment]
Fixed, wrong shortcode in wellbet post.

**Comment by diplomod** [comment]
:)
