### ISSUE TITLE
Linebreaks are not displayed correctly

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#52]
![2014-12-26 18 54 39](https://cloud.githubusercontent.com/assets/7487883/5558795/0224f6b2-8d35-11e4-9379-8fb2639ce963.png)

**Comment by mladjan** [comment]
Is the problem [wpsqt tag or something else? Line breaks are done automatically, because this is web view of content we have on website.

**Comment by diplomod** [comment]
Exactly - the "[wpsqt ... " is the problem. The text does not really make sense, does it?

Line breaks are not done at all. Please compare to web, e.g. http://dokuhl.de/geonova/well-bet-page/test-wellbet-app-ii/

**Comment by mladjan** [comment]
[wpsqt] tag is filtered.
Also, about breaklines, you are using on the web "\r\n" for new line (or text editor uses it), but for HTML it's safer to use <br /> tag. I'm changing it in the fly right now.

**Comment by diplomod** [comment]
looks great, thanks,

**Comment by diplomod** [comment]
Now they're back again:
![2015-01-05 15 38 12](https://cloud.githubusercontent.com/assets/7487883/5614697/eed5d862-94f3-11e4-8de6-3ce9d0d75dce.png)
![2015-01-05 15 13 27](https://cloud.githubusercontent.com/assets/7487883/5614702/f6a76a24-94f3-11e4-96cb-109ff3dc4622.png)

**Comment by mladjan** [comment]
Linkbreaks are done automatically like in any website. This content is generic and these links I can't map to some native screens

**Comment by diplomod** [comment]
Sorry for not getting it. But in the last build, the linebreaks as delivered by wordpress were displayed correctly in the app. Now they disappeared again.

**Comment by mladjan** [comment]
I just saw raw html I'm getting from wordpress (pasted at the end).

To make line break, you need to use HTML tag `<br />`, which means "break line".
In this example, you don't have it.

```
This WellBet is closed. The outcome is rather surprising.

The WellBet was a great success.

<a title="Garantiana Detailed Results" href="http://dokuhl.de/geonova/wellbet/closed-wellbets/garantiana-detailed-results/"><strong>See here the detailed results and more information about the prospect.</strong></a>

&nbsp;

The WellBet in this prospect was powered by <a title="About" href="http://dokuhl.de/geonova/about/">Geonova</a>.

&nbsp;

&nbsp;

&nbsp;
```

**Comment by diplomod** [comment]
@Immoz Apparently, our wordpress delivers suboptimal HTML. Can we change it so we make those hardcore linebreaks and give out the HTML that is also interpreted as linebreak by the app?
