### ISSUE TITLE
How can I change the banner at the bottom of the page?

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#54]

**Comment by mladjan** [comment]
Banner is hardcoded into app binary.

**Comment by diplomod** [comment]
I need to be able to change it. Is there a way to do that?

**Comment by diplomod** [comment]
I know you guys are working on a solution. Please keep in mind: The banner should be clickable, so we need to be able to set a hyperlink behind it.

**Comment by diplomod** [comment]
Is there a solution in the next build for changing the banner (+hyperlink)?

**Comment by mladjan** [comment]
Yes, I'm pulling banner image and url from our server (http://www.dokuhl.de/geonova/api/public/banner)
We can change these info anytime on the server. Right now we don't have any fancy admin tool because it's too much work to build one just for changing the banner image and url, so web devs can change this anytime on the server.

**Comment by diplomod** [comment]
Thanks!
@Immoz Who is our webdev? Can I make that myself?

**Comment by mladjan** [comment]
Our web developer (Mladen) :)

If you want to change it, image and url will be stored at: /public/banner/
Just rewrite image banner.png
URL will be in .txt document

P.S. Mladen is now changing something on the server to make this work, this will  be done in next 15-30min.

**Comment by diplomod** [comment]
Great - thanks. What is the correct size of the png-file?

**Comment by mladjan** [comment]
You can see example size, 640x100

**Comment by mladenbl** [comment]
Hi,

I just changed folder name from "banner" to "banner_content". Now content is in /public/banner_content/
