### ISSUE TITLE
No Push-Notification when a new WellBet is added

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#55]
When I added the app, I was asked whether I want to allow push notifcation. Yet I don't get any.
At least when a new WellBet is added there should be a push notifcation.
ALso when a comment has been added to any wellbet(see also #50 )

**Comment by mladjan** [comment]
I was talking with Michael about this, and he told me that we will have only manual sending push notifications. 
When you want to send new push notification, you can use this url: https://parse.com/apps/geonovawellbets/push_notifications/new

**Comment by diplomod** [comment]
Yes, that's fine. 
2 questions:
1) The push is shown on the phone and in the message center. But the icon does not get the red number of push notifications. (compare to the icon of WellBet right bottom with e.g. the icon of messages). Is this possible?

![2014-12-29 20 07 28](https://cloud.githubusercontent.com/assets/7487883/5572623/5d413754-8fa1-11e4-8f37-7f422a38a675.png)

2) What does this mean:
"Increment App Badge"?
