### ISSUE TITLE
Comment button not transparent in any WellBet

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#56]
In WellBets where I have placed a bet already, the "Place your bet" button is transparent=inactive. This is fine.

but the comment button is transparent, too, which is not correct because the commenting function should be available any time, regardless whether the user has placed a bet in this bet or not.

![2014-12-29 20 01 09](https://cloud.githubusercontent.com/assets/7487883/5572987/1776eeda-8fa6-11e4-81ca-76d935783b52.png)

**Comment by mladjan** [comment]
It just looks like transparent, but the color is the same for both screens. If you pick the color with color picker, you will see :)
Only think I can do is to change this color.
