### ISSUE TITLE
Add some space on the sides

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#57]
Content is squeezed and sometimes words are cut off - so a little bit of space on the sides would be good:

![2014-12-29 20 01 09](https://cloud.githubusercontent.com/assets/7487883/5573001/3d4fd752-8fa6-11e4-8700-f2ddf8866a75.png)

See "ago" in the top line
![2014-12-29 19 56 43](https://cloud.githubusercontent.com/assets/7487883/5573003/45fbf908-8fa6-11e4-82e7-5c8e370bd302.png)

Strangely, some are displayed with more space:
![2014-12-29 20 04 10](https://cloud.githubusercontent.com/assets/7487883/5573010/5f417b40-8fa6-11e4-82a0-e580e492f2ea.png)

**Comment by mladjan** [comment]
I think I fixed them all in build 12.

**Comment by diplomod** [comment]
Looks very good on all pages now!
