### ISSUE TITLE
"See details" => directly to "Prospect details"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#59]
When I click on "See details" I come to the screen with the text "You can place your bet ... " and the two buttons "Prospect details" ans "Place your bet" (inactive". This does not make sense.
Users should be directed straight to the screen behind "Prospect details".

**Comment by mladjan** [comment]
What about this task? https://github.com/diplomod/WellBet-App/issues/64

**Comment by mladjan** [comment]
@diplomod  what to do here? We have this issue, and issue #64 and they are contradictory.

**Comment by diplomod** [comment]
Correct - we go for #64 (assuming that we can show my personal bet)
