### ISSUE TITLE
Comments - Connection error

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#6]
I can't comment:

![image 5](https://cloud.githubusercontent.com/assets/7487883/5165438/b36ddc5a-73e4-11e4-9e26-af9229a830e8.png)

**Comment by mladjan** [comment]
This now should work, test it again in new build.

**Comment by diplomod** [comment]
Does new build mean I should delete the app and re-install?

**Comment by mladjan** [comment]
Yes

**Comment by diplomod** [comment]
Nope, not at all:
![image](https://cloud.githubusercontent.com/assets/7487883/5221064/c3856c5e-7671-11e4-97a3-efe9cc6019e7.png)

**Comment by mladjan** [comment]
The same like placing a bet bug.
