### ISSUE TITLE
Results: Some or any of my votes are not highlighted in green

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#61]
Here, any are highlighted:
![2014-12-29 19 49 41](https://cloud.githubusercontent.com/assets/7487883/5573079/4306530a-8fa7-11e4-8edb-9384241cc719.png)

Here, only a few:
![bild2](https://cloud.githubusercontent.com/assets/7487883/5573104/b23121e2-8fa7-11e4-8693-100ad12276a3.jpeg)

Works in the web version

**Comment by mladjan** [comment]
The problem is, that I know my votes only when I'm showing results screen after my vote. If I show this screen directly from dashboard, I don't know what I voted on this wellbet. This is a technical limitation.

**Comment by diplomod** [comment]
OK - but the user is logged in and the DB should be telling us what the user has been voting on, doesn't it?

**Comment by mladjan** [comment]
Yes, we know everything about that user, but what he voted we doesn't know when we are returning results. Mladen (our API developer) told me that plugin for wordpress (voting) doesn't giving him this info.

**Comment by diplomod** [comment]
I don't get it - on the web version, the system always remembers which bets I have already placed a bet and the details of my individual bet. 
@mladjan Have a look at the performance of the system on the web: http://www.geonova.no/well-bet/ 
Apparently, there is information which cannot be accessed through the API for the app. In that case, we need support from @Immoz 
Anyway, please check if that is actually the case.

**Comment by Immoz** [comment]
This part was implemented by Kevin but maybe you can retrace the workflow for getting votes of the current user by having a look on his code (line 98 and previous):
\geonova\wp-content\plugins\WP-Survey-And-Quiz-Tool-master\lib\Wpsqt\Page\Main\Results\Poll.php
