### ISSUE TITLE
"See my bet" instead of inactive "Place your bet"-button

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#64]
All ets where I have placed my own bet, I cannot see my personal bet again.

We should show instead of an inactive "Place your bet"-button a button that says "See my bet" and show the results page which I get after I have submitted my bet.

This is very important.

**Comment by mladjan** [comment]
Added in build 12.

**Comment by diplomod** [comment]
Sorry... :) Can we make "Show my bet" instead of "See my bet"?

**Comment by mladjan** [comment]
Changed
