### ISSUE TITLE
Results don't work for closed bets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#65]
For some reason, I cannot access the results page for closed bets.

I double checked with the web version, cleaned out results, checked the shortcode, and tried again, but can't see the result page:

![bild3](https://cloud.githubusercontent.com/assets/7487883/5573204/631d1c30-8fa9-11e4-903a-24226c6c6f7b.jpeg)
![bild4](https://cloud.githubusercontent.com/assets/7487883/5573205/631dc48c-8fa9-11e4-923b-a746fdae5b21.jpeg)

**Comment by mladenbl** [comment]
Hi,

Problem is in shortcode, when you close wellbet and remove shortcode from post content i can't get results for quiz because i don't know which one you used. What do you think about creating custom value textbox in wordpress where you can enter quiz name when you close it ,and then i can pull results based on that?

**Comment by diplomod** [comment]
Thanks for the info. I don't get it, but Tom who deployed the plugin eventually can help.

@Immoz Tom, can you evaluate this suggestion and let us know if this could a) solve the problem and b) could be done from your side. Thanks!

**Comment by Immoz** [comment]
Yes, we could do this and I'm sure this would solve the problem.

**Comment by diplomod** [comment]
@Immoz Thanks - please discuss with Philip if you can deliver this today or tomorrow.
@mladjan Would that work for you?

**Comment by mladjan** [comment]
Yes, @mladenbl will be able to fix the problem if we have some custom field with shortcode.

**Comment by Immoz** [comment]
Hi, i added the input box for the wellbet shortcode. I hope this helps you further.
![2015-01-04 16_51_50-edit post geonova wordpress](https://cloud.githubusercontent.com/assets/1924026/5606506/941a78f4-9432-11e4-8163-20ef35956630.png)

**Comment by mladenbl** [comment]
Fixed with this custom field, just add shortcode to it when you close/open wellbet.

**Comment by diplomod** [comment]
Thanks. Do we need to add the shortcode in the field
1) on top to the shortcode in the description and
2) to all "old" WellBet?

**Comment by mladenbl** [comment]
1) Yes
2) Yes, if you don't add it they will not work

**Comment by mladjan** [comment]
It's ok right now.

**Comment by diplomod** [comment]
works fine now
