### ISSUE TITLE
Open WellBets blank after submitting bet

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#68]
There are several open bets. But when I submit a bet on one of them, the entire section is blank:

![2015-01-05 15 17 27](https://cloud.githubusercontent.com/assets/7487883/5614735/6ae9f0e6-94f4-11e4-8158-88b1543cfa84.png)

**Comment by mladjan** [comment]
Maybe you wasn't logged in before that? If you remove app, install it again, log in, return to that screen (before you done betting), you will see these bets. I just tested this, it works as expected.

**Comment by diplomod** [comment]
Well, it happened again, but only with one of my testusers. With the other one it works just fine. We leave it for now.
