### ISSUE TITLE
Placing a bet - Connection error

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#7]
I can't place a bet:

![image 7](https://cloud.githubusercontent.com/assets/7487883/5165442/cb28177a-73e4-11e4-9a9f-dd9326a56816.png)

**Comment by mladjan** [comment]
This now should work, test it again in new build I sent.

**Comment by mladjan** [comment]
I think this was login issue, now this should work. Please reopen this issue if you get this issue again.
