### ISSUE TITLE
Hide link to results page on web

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#71]
Is there a way how we can hide the link to the results page on the web?
It is always included in the text when a bet has been closed. But users will click first on the link that says "See the detailed results..." and get to the webpage rather than clicking on the "See results" button at the bottom of the page.
![2015-01-05 15 38 12](https://cloud.githubusercontent.com/assets/7487883/5614812/1899acfe-94f5-11e4-869a-0cedbd3e462a.png)

**Comment by mladenbl** [comment]
There is no any unique identifier that i can use to remove that link, only if you add some unique id, class or something to that link i will be able to remove it. Currently i can only remove all links.

For example:

Currently link is like this:

```
<a title="Garantiana Detailed Results" href="http://dokuhl.de/geonova/wellbet/closed-wellbets/garantiana-detailed-results/"><strong>See here the detailed results and more information about the prospect.</strong></a>
```

If we add " id='details-link' " to it and link become like this

```
<a id="details-link" title="Garantiana Detailed Results" href="http://dokuhl.de/geonova/wellbet/closed-wellbets/garantiana-detailed-results/"><strong>See here the detailed results and more information about the prospect.</strong></a>
```

I will be able to remove it.

**Comment by diplomod** [comment]
Thanks for the feedback - I guess this would be feasible, but I'm worried that we will make mistakes and then it does not work and we search for ages for the mistake...
@Immoz Could we adopt the WellBet admin page accordingly? Adding a fixed field for the link to the results page?

**Comment by Immoz** [comment]
Sure, this would be no problem.

**Comment by diplomod** [comment]
OK @Immoz please add that field.
Can we then have as standard a green button at the bottom of the text, saying 
"Detailed results of this WellBet and information on the prospect"

And since we're working on it, can you also add the sentence below this button then:
"Learn more about Geonova’s WellBet – powered by Atlantic Petroleum here." ("here" is linked to http://www.geonova.no/well-bet/about-wellbet/)

![screen shot 2015-01-06 at 20 02 17](https://cloud.githubusercontent.com/assets/7487883/5634319/0e0b66ca-95df-11e4-9a1d-6139a6608f6e.png)

**Comment by mladjan** [comment]
What is the action for that button? This is HTML, and we are loading this into native app, so we are limited with technology a little bit, all links needs to be handled manually.

**Comment by diplomod** [comment]
The button is a link to a page which is created after a WellBet is closed. We do this extra page as we replace the original content with a simple summary of the outcome and only link to the poll results.
See e.g. here: http://www.geonova.no/well-bet/closed-well-bets/wellbet-kopervik-prospect-details/

Now in the App, we are showing the summary and link to the detailed results. So we don't need to guide the users to that extra page. That's why I want the link to be hidden.

**Comment by Immoz** [comment]
The field for the summary-url is added.

**Comment by mladjan** [comment]
This is done on server side?

**Comment by diplomod** [comment]
@Immoz ??

**Comment by mladjan** [comment]
@mladenbl ?

**Comment by mladenbl** [comment]
I just added details link to object, but you will need to integrate this solution to website also, because i can't remove that link from content(explained in my last comment). You will need to add details link in custom field and remove it from post content, and then on website you will need to pull that link from custom field and display it. I hope that you understand me.

**Comment by diplomod** [comment]
@Immoz Go go go

**Comment by Immoz** [comment]
I implemented this on the dokuhl server. If you mark a wellbet as closed in the admin-panel and insert the summary-url into the provided field - the button and info-text will be automatically added at the bottom of the content. (see result here http://dokuhl.de/geonova/well-bet-page/332-1-saturn/ )

@diplomod just tell me when i should upload this on the live server. Because after i uploaded this, maybe the content of all wellbets need to be manually conformed (removing doubled links to summary-pages).

**Comment by diplomod** [comment]
@audriunas Please check all WellBets, take out the link in the text and place it in the special new field:
![screen shot 2015-02-16 at 17 47 17](https://cloud.githubusercontent.com/assets/7487883/6215811/31480bb2-b604-11e4-9507-1b17c3e441a1.png)
![screen shot 2015-02-16 at 17 50 00](https://cloud.githubusercontent.com/assets/7487883/6215818/4af76d8c-b604-11e4-84c2-e6a87fa55541.png)

**Comment by mladjan** [comment]
Check if this works in v1.1

**Comment by diplomod** [comment]
Looks very good - thanks
