### ISSUE TITLE
Please add new tester

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#74]
audreynorkus@gmail.com

**Comment by mladjan** [comment]
New tester needs to add his device first, and after that I will be able to add his UDID into next build. But I hope we will finish with testing and send this to AppStore in some point of time :D

**Comment by diplomod** [comment]
OK - what means to add the device again? I already forgot :)
Audrius will only test as soon as we are on the live server

**Comment by mladjan** [comment]
Done this already, sent the build twice.

**Comment by diplomod** [comment]
:)
