### ISSUE TITLE
Closed WellBets should stay in "My WellBets"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#76]
Is it possible to keep all WellBets in "My WellBets", also when they're closed?
Sorted chronologically, with the one where I placed a bet latest on top.
![2015-01-06 20 55 29](https://cloud.githubusercontent.com/assets/7487883/5635392/1bf1581c-95e9-11e4-8fc9-0175ef27c864.png)

**Comment by mladenbl** [comment]
They are already in my wellbets.

**Comment by diplomod** [comment]
OK - I was under the impression that they disappear from my WellBets when bets are closed, but I guess it's correct if you say so. Let's have an eye on it when live :)
