### ISSUE TITLE
Prospect details in closed bets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#78]
We should have a link to "Prospect details" also in closed bets, just as we have it in the open bets.
Now I know that this is tricky because the content behind that button is sourced from the original wordpress page when the WellBet is created, but this page is changing when the WellBet is being closed.

So what we would need is actually an extra field in the Wordpress system for "Prospect details" which remains unchanged.
@mladjan If we have a field like that, can you then source the content for "Prospect details" from there directly and also show it in closed bets (button below "See Detailed Results"-button)?
@Immoz If Mladjan can make use of such a field, can you create such a field in the Wordpress system? 

![2015-01-06 21 21 26](https://cloud.githubusercontent.com/assets/7487883/5635524/1ea1d8a6-95ea-11e4-92de-8ac0fd1260c3.png)

**Comment by mladjan** [comment]
@mladenbl can check this, but I think we don't have this data.

**Comment by diplomod** [comment]
@Immoz Your feedack please

**Comment by Immoz** [comment]
Yes i could add such a field.

**Comment by diplomod** [comment]
Excellent. I'll get in touch with you regarding the effort.
@mladjan You have not privided feedback yet if this would work for you. Please let us know.

**Comment by mladenbl** [comment]
I can pull data from custom field based on post ID. When you create that field please send me a name of it.

**Comment by diplomod** [comment]
@Immoz Go go go :)

**Comment by Immoz** [comment]
Hi, i reviewed this issue and if i understood this right we can use the field "wbsummarylink" for closed bets as well as for open bets to set a link to wellbet-prospects. @mladenbl if you need to pull data based on post ID maybe you can just use this method? http://codex.wordpress.org/Function_Reference/url_to_postid

**Comment by diplomod** [comment]
@mladjan Here we need the following: In closed bets should be a second button below the button "See detailed results"  that says "Prospect details" - just like in open bets. This content is sourced from this field:
![screen shot 2015-02-16 at 18 19 52](https://cloud.githubusercontent.com/assets/7487883/6216264/797c8c24-b608-11e4-8aa8-79e221bf24d8.png)

**Comment by mladjan** [comment]
Done in v 1.1

**Comment by diplomod** [comment]
Great, thanks.
@audriunas Please check if all links are placed correctly. Seems to work for old bets already, but better check.
