### ISSUE TITLE
Hyperlinks in text don't work

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#8]
When I click the link in this text, nothing happens:

![image8](https://cloud.githubusercontent.com/assets/7487883/5165446/df033f86-73e4-11e4-9168-1cfb0994d0b7.png)

Anyway, I presume this is copy-paste from the website. We need to change this particular text anyways. But in genereal, weblinks should open my default browser.

**Comment by mladjan** [comment]
These links are still "open", because I think they need to link to some screens in the app, for example "See all ongoing bets here" link should points to all bets screen. What about other urls here on this page? To open them in safari?

**Comment by diplomod** [comment]
It depends on where I edit the text. Can I edit text somewhere and link to screens within the App or is it only you who can do it.

Regardless, normal links to external sites should always open in the default browser (on Iphone Safari, on others I don't know)

**Comment by mladjan** [comment]
Ok. For this screen "More info" and for "terms and conditions" we have static pages preloaded into app, and they can't be edited on the server. In this case, I linked first link to the main page, and all other will open in safari (but I don't have the url for second one on this page).

All other pages like details for betting, are edited on the server (wordpress admin page) and they will open all urls into safari.

**Comment by diplomod** [comment]
Safari does not open for external links.

**Comment by mladjan** [comment]
Ok, More info now has two links, one for all open bets, and one for all closed bets.
Terms and conditions doesn't have any url.

Every external URL will now open in Safari. Images are separate issue (#5).

**Comment by diplomod** [comment]
The 2nd link ("Learn about the outcome of all completed bets here.") does not work.
![2014-12-08 07 11 35](https://cloud.githubusercontent.com/assets/7487883/5335580/47bf1248-7ead-11e4-960c-779805d7e189.png)

**Comment by mladjan** [comment]
Did you tried last version of the app? This link works on my phone.

**Comment by diplomod** [comment]
I just installed it again, but the link does not work.

**Comment by mladjan** [comment]
The same thing, next build (6). You will get email when I send new build.

**Comment by diplomod** [comment]
Nope, still does not work, V6 neither.
The link reacts now with a quick highlight of the text, but no page opens-

**Comment by mladjan** [comment]
That was iOS7 issue, fixed in next build.
