### ISSUE TITLE
Comments for closed WellBets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#80]
Can we add the comments-button at the bottom of the page of closed WellBets? (below button "See Detailed Results")
Comments are in particular important when the WellBet has been closed.
![2015-01-06 21 21 26](https://cloud.githubusercontent.com/assets/7487883/5635579/81ef6054-95ea-11e4-8c23-ecb5800f4dda.png)

**Comment by mladjan** [comment]
This will take few additional hours of work. I can do this, but you should check this with Michael.

**Comment by diplomod** [comment]
OK - next Update - extra

**Comment by mladjan** [comment]
Done, it will be available in build 19, version 1.1

**Comment by diplomod** [comment]
Phantastic - thanks
