### ISSUE TITLE
Can we remove the scrolling in the results?

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#82]
Why don't we use the full page here instead of the tiny scrolling?
![foto](https://cloud.githubusercontent.com/assets/7487883/5662731/68de1796-973d-11e4-9a9b-73e9e2645764.png)

**Comment by mladjan** [comment]
We have more content then space on the page, this is why we are using scrolling.
Why? Because Igor designed it to work like this and you approved it :)

**Comment by diplomod** [comment]
OK - but still it does not make sense. I'll check with Michael.

**Comment by audriunas** [comment]
On iphone 5 you cannot see questions of the poll fully and you cannot slide to the sides. Only up and down.

**Comment by mladjan** [comment]
Ok, scrolling is now in one peace, and questions fill fit right now.
