### ISSUE TITLE
Wrong frame size in closed WellBets

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#83]
frame size seems to be fixed under ‘My Wellbets’ but if you check closed ones under ‘Closed Wellbets’ you see this:
![img_0114](https://cloud.githubusercontent.com/assets/7487883/5662755/bb5418c2-973d-11e4-92bc-eabb1bd4c926.png)
iPhone 5c

**Comment by mladjan** [comment]
Which iOS version you have on iPhone 5c? I tested it on iPhone 5 and it looks fine.
Please test again this new build (16) and let me know if this happen again.

**Comment by audriunas** [comment]
Tested with the new build (16). It's the same. iOS 8.1.2.

**Comment by mladjan** [comment]
I hope in build 18 this is ok: http://cl.ly/image/0v3h0c0z0n2p
