### ISSUE TITLE
Keep bets in "My WellBets" and "Open WellBets"

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#88]
Keep bets also in "Open WellBets" after placing a bet as lon as they are open. It is confusing when I have placed a bet and then "Open WellBets" is suddenly empty.
![2015-01-28 00 09 56](https://cloud.githubusercontent.com/assets/7487883/5934637/5b5dc72a-a6d2-11e4-8ff3-1ef5ea3f8c54.png)

**Comment by mladjan** [comment]
@mladenbl can do this

**Comment by mladenbl** [comment]
Fixed
