### ISSUE TITLE
App has problems with wordpress toolbar toggle

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#89]
In Zulu WellBet we have integrated a toolbar toggle/text box in the description.
It is interpreted incorrectly by the app - the screen can be scrolled to the side as the text in the boy apparently is not fitted in:
![screen shot 2015-01-28 at 09 06 11](https://cloud.githubusercontent.com/assets/7487883/5934580/88dba1f0-a6d1-11e4-8a92-b9e9a4cd3706.png)
![2015-01-28 00 08 16](https://cloud.githubusercontent.com/assets/7487883/5934590/a882ba16-a6d1-11e4-8d6a-b92ae127672b.png)

**Comment by mladjan** [comment]
I can't see this WellBet because it's completed. Please, give me HTML example how this looks, and I will add css in the app to style this.

**Comment by diplomod** [comment]
@Immoz Please help me out here - I don't even know where to look :)

**Comment by Immoz** [comment]
It seems the textbox is still here included http://www.geonova.no/well-bet/closed-well-bets/wellbet-zulu-prospect-details/

Probably the problem is caused by the "pre"-tag. Maybe you can simply replace those tags by div's or something else? Otherwise just let me know if there needs to be something adjusted on php-side.

**Comment by diplomod** [comment]
@mladjan Thanks for feedback

**Comment by mladjan** [comment]
Hi guys,

I can't see this anymore in the app because app can't get this html. I done some CSS without testing, so you can check somehow.

**Comment by diplomod** [comment]
Still there. Let's bury it, no big deal.

@audriunas We don't get this under control - I understand this is really tricky. Let's just not use the grey boxes - end of discussion.
