### ISSUE TITLE
Title too long

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#9]
We need to make sure that we can read the titles.
The one title of the example ("Place your bet on the Ivory Prospect", 36 characters) is longer than usual. 

![image 2](https://cloud.githubusercontent.com/assets/7487883/5165489/7b343c2a-73e5-11e4-87b5-09a9ecf1fa0c.png)

Normally, the standard is like this: "30/11-10 Krafla North" (max. 25 characters)

What's the maximum length?

**Comment by mladjan** [comment]
We can reduce font size in this situations where it can't fit

**Comment by diplomod** [comment]
that would be great

**Comment by mladjan** [comment]
Ok, done.

**Comment by diplomod** [comment]
Resolved, nice
