### ISSUE TITLE
Pictures are not shown

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#90]
It is only shown the same picture for all pictures.
Here, this onw should be shown:
![screen shot 2015-01-28 at 09 01 52](https://cloud.githubusercontent.com/assets/7487883/5934598/ca8e7794-a6d1-11e4-90ea-73c77e271cc9.png)
But we see this one again (it's the first picture):
![2015-01-28 09 01 48](https://cloud.githubusercontent.com/assets/7487883/5934605/ee80ab22-a6d1-11e4-9b77-9ce8e0ce0f58.png)

**Comment by mladjan** [comment]
I'm getting these pictures in HTML: http://cl.ly/code/2a2z3R1q2F13
Will check with API developer too.

**Comment by diplomod** [comment]
I cannot aee the picture, Pleas epost it here. Anyway. it does not work for mw. this is very important.

**Comment by mladjan** [comment]
Also, the same problem like in previous issue: http://cl.ly/image/1R150j243B0j
This is the HTML I'm getting from your wordpress site. As you can see, all image urls are the same. I don't have anything with this, this is wordpress editing issue.
