### ISSUE TITLE
App does not recognize my data

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#91]
I have placed a bet with this user on both wellbets already on the web. But the App allows me to place a new bet through the app. I wonder if the app does not get the right info from the database:
![2015-01-28 00 08 34](https://cloud.githubusercontent.com/assets/7487883/5934619/26111cca-a6d2-11e4-8589-e2ae465ee6c2.png)

**Comment by mladjan** [comment]
@mladenbl will check that

**Comment by mladjan** [comment]
I checked this and it works fine at my phone. When you place a bet on some bet online, you need to reload data on you device, or to open app again. I don't have real information if something is changed on the server.

**Comment by diplomod** [comment]
I believe it does. We'll realize it if it is a real issue. Nothing to worry about now.
