### ISSUE TITLE
Pingback comments

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#92]
@Immoz The pingbacks look like a error in the comments. I would like to keep them as they are links to interesting aricles usually. Can we optimize this in a way that is usually says "Read this article related to this here: URL"?

**Comment by mladjan** [comment]
Will check with API dev (@mladenbl)

**Comment by mladjan** [comment]
@mladenbl will check that

**Comment by mladenbl** [comment]
Added, please check it now.
