### ISSUE TITLE
Clean formatting in Wordpress

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#93]
@Audrius 
We ust make sure that the content in wordpess is formatted as clean as possible and as little spaceous as possible.
Here I had to clean the text as wordpress provided several hidden linebreaks (I do this by cutting the text from wordpress, pasting it into e.g. Google search field, copy+paste back into Wordpress -> Google search fields cleans all formatting):
![2015-01-28 00 07 58](https://cloud.githubusercontent.com/assets/7487883/5934682/f2a65534-a6d2-11e4-90cb-eb78a64bde09.png)

**Comment by audriunas** [comment]
Alright, I'll have that in mind.
