### ISSUE TITLE
Headlines bold

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#94]
It would be very good for the overview if the app interprets bold font as such:

e.g. Johann Sverdrup is bold in Wordpress, in the app I see no difference

![2015-01-28 09 01 35](https://cloud.githubusercontent.com/assets/7487883/5934720/659f4514-a6d3-11e4-8f49-7b4f3ce4998e.png)

**Comment by mladjan** [comment]
Also, this is HTML just rendered in embedded safari. Can you copy/paste me this tag from HTML? Bold can be defined in HTML on different ways.

**Comment by diplomod** [comment]
I send you a txt file (if I copy paste here, it shows the same as on he webpage)

**Comment by mladjan** [comment]
Ok, you are using <strong>. Added styling for string too.

**Comment by diplomod** [comment]
... and that means?

**Comment by mladjan** [comment]
It will be visible for you in next build
