### ISSUE TITLE
Hide intro

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#95]
This intro is misleading and takes lots of space. We should start with the description right away:
![2015-01-28 00 06 59](https://cloud.githubusercontent.com/assets/7487883/5934744/8e1b1928-a6d3-11e4-8f31-2c9cd9364161.png)
WOrst case is that people click on the link and come to the web version even before they see the button "Place your bet"

If it is possible, I suggest you cut out everything above "INFORMATION ABOUT THE PROSPECT" in all bets

**Comment by mladjan** [comment]
All informations shown here are HTML we are pulling from wordpress database. Data is not consistent and any cut of data is working in the dark. All filtering can be done on API side.

**Comment by diplomod** [comment]
OK - I don't quite understand. What is the API side?

**Comment by mladjan** [comment]
We built API, middle man between wordpress database and iOS app. This part of the code is pulling data from database, filtering data, and forwarding data to the app.

**Comment by diplomod** [comment]
OK - so can you cut it off or not?

**Comment by mladjan** [comment]
No, because this is something just for this wordpress post, this is not repeatable on all posts.
You need to open this post in wordpress, see HTML code (or somebody who knows HTML well) and remove <br /> tags or anything other what makes this space.

**Comment by diplomod** [comment]
@Immoz Can we optimize this in the Geonova system? Apparently the HTML that our editor delivers cannot be interpreted correctly by the app.

**Comment by Immoz** [comment]
If i am right, the content above "INFORMATION ABOUT THE PROSPECT" and the shortlink to the poll should be always the same? So we could build only one editor field where you can set this content and let this content automatically show on all open well-bets. With this you not always need to copy+paste this content. Additionally we can surround this content by a "box" (div) with an ID which should be easily removable by the API.

**Comment by Immoz** [comment]
Or to be precise you not even need to remove this "box" if you only fetch the well-bet post content. (unnecessary content is already excluded)

**Comment by diplomod** [comment]
great , thanks.

@mladjan Can we work with that?

**Comment by mladjan** [comment]
Hi,

this is html issue.
From the server, I'm getting this html content: http://cl.ly/image/1R150j243B0j
This space is making one empty <p> tag and 2 <br /> tags: <br /><p> </p><br /><p>

If you clean this from post content in wordpress, this will be fixed. If you switch to "Text" mode, you will be able to edit pure HTML: http://cl.ly/image/3d2E372E2R3f

**Comment by diplomod** [comment]
@Immoz Please review and let me and @audriunas know 1) what exactly to change in the existing ones and 2) what to do differently in the future

**Comment by audriunas** [comment]
test comment.

**Comment by diplomod** [comment]
@mladjan We will extract the text (which I want to be out on top) in an extra field. For you, nothing should change since the information for the app is still sourced from the same field.

**Comment by Immoz** [comment]
Ok there are 2 problems within this issue. I will take care about extracting the top content so you will have no effort with this.

@mladjan 
I think the second problem with the big spacing should be handled somehow by your api (replacing linebreak tags) or css because for me it seems not to be reasonable and necessary to adjust all contents manually.

If this is really not possible it would be very helpful if you could do some testings within the app and find out which tags exactly causing the problem.

Is it e.g.
- `<p><br /></p>`
- `<p>&nbsp;</p>`

or just?
- `<p></p>`
- `<br />`
- `&nbsp;`

**Comment by Immoz** [comment]
@diplomod the intro-text for wellbets is now outsourced (Admin: Appearance->Geonova-Extra-Content) and will be only shown on open wellbets. It's alread uploaded on dokuhl, just tell me when i should upload this on the live server. Accordingly to https://github.com/diplomod/WellBet-App/issues/71 there need to be done some manual adjustments to wellbets after i uploaded this.

![2015-02-12 12_14_50-program manager](https://cloud.githubusercontent.com/assets/1924026/6166591/ac1d9f42-b2b1-11e4-89d7-06583433a26e.png)

**Comment by diplomod** [comment]
@Immoz Excellent - thanks. Looks good on dokuhl. Please upload to live
@audriunas: Can you edit the accordingly when it's on the live system and then edit the current open WellBet on Romeo accordingly?

**Comment by Immoz** [comment]
Ok its on the live server. Please also keep in mind that the link to wellbet-prospect needs to be inserted in the field "WellBet summary link" in order to generate the button which links to the prospect details (https://github.com/diplomod/WellBet-App/issues/71).

![2015-02-12 13_06_56-program manager](https://cloud.githubusercontent.com/assets/1924026/6167188/ed8dad3a-b2b8-11e4-80ac-74fd69f34823.jpg)

**Comment by diplomod** [comment]
@audriunas Tom has a point - I think we need to copy this link in all WellBets, also the closed ones. Can you take care of that, too?

**Comment by audriunas** [comment]
![geonova](https://cloud.githubusercontent.com/assets/10405035/6172333/635f9e34-b2e0-11e4-9dc1-ef22d25ba6f6.PNG)
Got this when tried to save changes with new 'Intro text for wellbets'.

**Comment by Immoz** [comment]
I tested this and it seems to work for me. ("Intro-test" was successfully stored)
![2015-02-12 18_10_44-geonova-extra-content geonova wordpress](https://cloud.githubusercontent.com/assets/1924026/6172729/dbb3e244-b2e2-11e4-9507-7124f8a62188.png)

Is it possible that you got logged out or something?

**Comment by audriunas** [comment]
Tried again today using my mac with different browsers. Got the same message. Can it be somehow related with my rights on the website?

**Comment by diplomod** [comment]
You've just got promoted to Admin :) Try again - could very well be

**Comment by diplomod** [comment]
@audriunas Is it working now?

@mladjan Could you please provide feedback to @Immoz regarding the linebreak tags?

**Comment by audriunas** [comment]
@diplomod yes, it works now.

**Comment by mladjan** [comment]
Is this done? Why am I still assignee?

**Comment by audriunas** [comment]
All the links are in the right place now.

**Comment by diplomod** [comment]
@mladjan sorry, forgot to change the assigne :) 
@audriunas Thanks, looks very good now
