### ISSUE TITLE
Open external URLs within the app

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#96]
Is there a way to open external links within the frame of the app?
The problem is that Iwhen I open an external link form the app, my webbrowser opens. In order to get back, I need to close the webbrowser and re-open the app. 
It would be better if I had a possibility t get back to the app with one click.

**Comment by mladjan** [comment]
Yes, it's possible, but it will take few hours of work.

**Comment by diplomod** [comment]
OK - I'll clraify with Michael

**Comment by diplomod** [comment]
We agreed that this is extra - comes later

**Comment by mladjan** [comment]
Done in version 1.1
