### ISSUE TITLE
Pictures in prospect detailes mixed up/don't show

### ISSUE THREAD

**Issue by audriunas** [diplomod/WellBet-App#97]
Seems like we have the same issues after uploading new wellbet.

![image1](https://cloud.githubusercontent.com/assets/10405035/6214826/d35662ea-b5fb-11e4-90a8-07655c2da2ba.PNG)
![image2](https://cloud.githubusercontent.com/assets/10405035/6214831/d8e459a6-b5fb-11e4-8470-231104630954.PNG)

Grammar mistake - 'infomration'.
Area of poll isn't excluded.
Doesn't recognise second picture.

**Comment by diplomod** [comment]
@audriunas I have taken out this content as it is not necessary:
![screen shot 2015-02-16 at 18 23 05](https://cloud.githubusercontent.com/assets/7487883/6216296/f6d8d696-b608-11e4-9cdd-181df554190f.png)

@mladjan This content should not be included either. The heading "Information about the prospect" is repeated. The heading "Name of the prospect" is displaced and repeated below anyways.
![screen shot 2015-02-16 at 18 22 53](https://cloud.githubusercontent.com/assets/7487883/6216307/292fbc54-b609-11e4-8153-4cc60f45061a.png)

**Comment by mladjan** [comment]
Grammar mistake - 'infomration'.  - Done
Area of poll isn't excluded. - What area? 
Doesn't recognise second picture. - I need more information here too.

**Comment by audriunas** [comment]
@mladjan don't bother about 'poll area'. the gap formed due to unnecessary text.

**Comment by diplomod** [comment]
The second picture in this WellBet is not shown. What is displayed is the first picture again.

We should see this one:
![screen shot 2015-02-18 at 18 52 03](https://cloud.githubusercontent.com/assets/7487883/6253095/47426dda-b79f-11e4-980f-cf2020878e29.png)

But we actually see this one twice:
![screen shot 2015-02-18 at 18 52 08](https://cloud.githubusercontent.com/assets/7487883/6253101/5148f952-b79f-11e4-8286-b14dafc24438.png)

**Comment by mladjan** [comment]
Can I get user/pass for wordpress admin (live server) and exact name of wellbet, so I can check that HTML? :)

**Comment by diplomod** [comment]
I promoted your user with the email address mladjan@blgrd.co to admin
The well with the pictures is Gemini: http://www.geonova.no/well-bet-page/161-24-gemini/

BTW: The well with the problem of the grey bos is Zulu: http://www.geonova.no/well-bet/closed-well-bets/wellbet-zulu-prospect-details/
![screen shot 2015-02-19 at 08 18 22](https://cloud.githubusercontent.com/assets/7487883/6262999/ef68db50-b80f-11e4-8687-13bbc4c947a4.png)
#89  - just in case you find out something

**Comment by mladjan** [comment]
Fixed, take a look at your current build

**Comment by diplomod** [comment]
great - can you also tell us what was the pronblem? Because it occurs in other wellbets as well.
@audriunas pay attention ;)

**Comment by mladjan** [comment]
It was the issue on the API side, not in wordpress :)
