### ISSUE TITLE
Links in "More information" don't work for non-registered users

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#98]
If I click on the link of "See all ongoing bets here" and "Learn about the outcome of all completed bets here" in the screen to which I get when I click on "More information" after opening the App for the first time, I get to the pages "Open WellBets" and "Closed WellBets", but an error message is shown:

![foto](https://cloud.githubusercontent.com/assets/7487883/6253527/523b70c6-b7a2-11e4-8571-25b6bf33486c.png)

Ideally, the users can see the WellBets and get to the login-page when they try to open one.

**Comment by mladjan** [comment]
This is not the restriction based on logged user. I see you had bad internet connection, and phone wasn't able to reach the server. Test this on stable Internet connection please :)

**Comment by diplomod** [comment]
Haha - ok. I had an excellent connection, but maybe too much at the same time.
